apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: azure-vote-front
spec:
  image: azureback2schoolacr.azurecr.io/azure-vote-front
  interval: 1m0s
  secretRef:
    name: azurebacktoschool-creds