apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: azure-vote-front
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  policy:
    semver:
      range: 1.0.x
  imageRepositoryRef:
    name: azure-vote-front
