apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - registry-credential-sync/brownbaggitopsaks/kustomize.yaml
  - ../../voting-app/automation
patches:
  - path: brownbaggitopsaks-image-repo.yaml
    target:
      kind: ImageRepository