apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - kustomize.yaml
  - flux-config-gitrepo.yaml
  - image-automation-components.yaml
  - image-update-automation.yaml
