apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - kustomize.yaml
  - flux-config-gitrepo.yaml

patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add 
      path: /spec/template/metadata/labels/aadpodidbinding
      value: brownbaggitopsaks-mi