apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - kustomize.yaml
  - flux-config-gitrepo.yaml

patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add 
      path: /spec/template/metadata/labels/aadpodidbinding
      value: /subscriptions/04109105-f3ca-44ac-a3a7-66b4936112c3/resourcegroups/brownbaggitopsaks-mi-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/brownbaggitopsaks-mi