apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: credentials-sync  # name must match the stub-resource in az-identity.yaml
  namespace: flux-system
spec:
  clientID: 88f3d70c-f261-4844-94cf-8f62c7e7eea3
  resourceID: /subscriptions/04109105-f3ca-44ac-a3a7-66b4936112c3/resourcegroups/brownbaggitopsaks-mi-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/brownbaggitopsaks-mi
  type: 0  # user-managed identity