apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/production/00
  postBuild:
    substitute:
      ENVIRONMENT: "production"
      CLUSTER: "00"